# Generated by Django 4.1.5 on 2023-01-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_slug'),
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='page_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
    ]
