# Generated by Django 4.1.5 on 2023-01-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_comment'),
        ('pages', '0002_alter_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('new_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new')),
                ('page_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
    ]
