# Generated by Django 4.1.5 on 2023-01-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='new_id',
            new_name='new',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='page_id',
            new_name='page',
        ),
    ]
