# Generated by Django 4.1.5 on 2023-01-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_comment_created_at_alter_comment_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Germen'), ('fr', 'Franc')], default='en', max_length=2),
        ),
    ]
