# Generated by Django 4.1.5 on 2023-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_comment_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
