# Generated by Django 4.1.5 on 2023-01-23 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_comment'),
        ('pages', '0011_alter_comment_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nComments', to='news.new'),
        ),
    ]
